// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt4kS8jsVYPF49284AuTcrk_XcwOQb4-g',
    appId: '1:252247751324:web:83b6b76198aa9eaba64b59',
    messagingSenderId: '252247751324',
    projectId: 'foodbridge-ai-f2dc0',
    authDomain: 'foodbridge-ai-f2dc0.firebaseapp.com',
    storageBucket: 'foodbridge-ai-f2dc0.firebasestorage.app',
    measurementId: 'G-YRQBCVBYP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZkZU8SUFIoZ2EDl9hrD46B9KaqtMfIM4',
    appId: '1:252247751324:android:f3cb8f8d154982c5a64b59',
    messagingSenderId: '252247751324',
    projectId: 'foodbridge-ai-f2dc0',
    storageBucket: 'foodbridge-ai-f2dc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEeGcdXcSNgR0r-gmuft_8j_nSSZd0B88',
    appId: '1:252247751324:ios:38ae024194bdf368a64b59',
    messagingSenderId: '252247751324',
    projectId: 'foodbridge-ai-f2dc0',
    storageBucket: 'foodbridge-ai-f2dc0.firebasestorage.app',
    iosBundleId: 'com.example.foodbridgeAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEeGcdXcSNgR0r-gmuft_8j_nSSZd0B88',
    appId: '1:252247751324:ios:38ae024194bdf368a64b59',
    messagingSenderId: '252247751324',
    projectId: 'foodbridge-ai-f2dc0',
    storageBucket: 'foodbridge-ai-f2dc0.firebasestorage.app',
    iosBundleId: 'com.example.foodbridgeAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt4kS8jsVYPF49284AuTcrk_XcwOQb4-g',
    appId: '1:252247751324:web:6cfa45ce22f63797a64b59',
    messagingSenderId: '252247751324',
    projectId: 'foodbridge-ai-f2dc0',
    authDomain: 'foodbridge-ai-f2dc0.firebaseapp.com',
    storageBucket: 'foodbridge-ai-f2dc0.firebasestorage.app',
    measurementId: 'G-2TCPNHRR2D',
  );

}